#ifndef MESH_DEFINES_H
#define MESH_DEFINES_H

#include "../sharedLib_defines.h"

#ifdef pfemMesh_EXPORTS
	#define MESH_API PFEM_EXPORT
#else
	#define MESH_API PFEM_IMPORT
#endif

#define MESH_NOEXPORT PFEM_NOEXPORT
#define MESH_DEPRECATED PFEM_DEPRECATED
#define MESH_DEPRECATED_API MESH_API MESH_DEPRECATED
#define MESH_DEPRECATED_NOEXPORT MESH_NOEXPORT MESH_DEPRECATED

#endif /* MESH_DEFINES_H */