#ifndef SIMULATION_DEFINES_H
#define SIMULATION_DEFINES_H

#include "../sharedLib_defines.h"

#ifdef pfemSimulation_EXPORTS
	#define SIMULATION_API PFEM_EXPORT
#else
	#define SIMULATION_API PFEM_IMPORT
#endif

#define SIMULATION_NOEXPORT PFEM_NOEXPORT
#define SIMULATION_DEPRECATED PFEM_DEPRECATED
#define SIMULATION_DEPRECATED_API PFEM_DEPRECATED_EXPORT
#define SIMULATION_DEPRECATED_NOEXPORT PFEM_DEPRECATED_NOEXPORT

#endif /* SIMULATION_DEFINES_H */
