#ifndef SOLVER_DEFINES_H
#define SOLVER_DEFINES_H

#include "../sharedLib_defines.h"

#ifdef pfemSolver_EXPORTS
	#define SOLVER_API PFEM_EXPORT
#else
	#define SOLVER_API PFEM_IMPORT
#endif

#define SOLVER_NOEXPORT PFEM_NOEXPORT
#define SOLVER_DEPRECATED PFEM_DEPRECATED
#define SOLVER_DEPRECATED_API SOLVER_API SOLVER_DEPRECATED
#define SOLVER_DEPRECATED_NOEXPORT SOLVER_NOEXPORT SOLVER_DEPRECATED

#endif /* SOLVER_DEFINES_H */
